### ISSUE TITLE
Special Pythagorean triplet

### ISSUE THREAD

**Issue by streamcode9** [Unstoppable1988/Exercises#13]
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>

For example, 3<sup>2</sup> + 4<sup>2</sup> = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

**Comment by Unstoppable1988** [comment]
Completed
