### ISSUE TITLE
Bug with change class quest

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#29]
https://dn.mail.ru/forums/showthread.php?t=52416&page=3
Не получается взять квест на смену класса волше 15ур. Беру кв в доступных, тыкаю "Ок", кв перемещается в побочные. По нему надо поговорить с Тианой. Подхожу к ней, тыкаю "Задания", а заданий нет вообще. Только кнопка "Назад". Отказывался от кв, подходил к ней - без толку, все равно нету кв. При этом над ее головой висит вопросительный знак. Перезаход в игру не помогает. Что делать?
I cant take wizzard change class quest 15 lvl. I take quest in aviable, click "Ok", quest moves to secondary. In that quest you need to talk with Tiana. I come to her, click "Quests", but no quests at all. Only button "Back".
I declined the quest, come to her - uselessly, there is still no quest. Herewith over her head hangs on sign question. Log out and log in doesn't help. What can i do?

#102 [Quest] Bug with change class quest in Dragon nest.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.7.2.3657 (64-bit)
**Steps to reproduce:**
1. Take lvl 15 wizzard.
2. Open aviable quests menu, and take quest to change wizzard class.
3. Come to Tiara and click on her to speak with her.
4. Click on "Quest"

**Expected result:**
Aviable some text to accept next steps in quest.
**Actual result:**
No any text in the window.

**Comment by streamcode9** [comment]
I can't take quest to change wizzard class at level 15. I take quest from the available ones, press "OK", quest goes to secondaries one. According to quest I should talk to Tiana. I come to her, press "Tasks", but no task is available. There is "Back" button only. I have tried to dismiss quest but it does not take any effect - there is no quest all the same.  Herewith there is question mark under her head. Game restart does not help. What should I do?
