### ISSUE TITLE
Can't log in game

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#30]
https://dn.mail.ru/forums/showthread.php?t=52416&page=5
Я создал персонажа : класс выбрал, ник придумал. Захожу в игру выбираю сервер Тиамат, потом выбираю зеленая застава. Он входит и черный экран. Показывает только проплывающие подсказки. Что делать? 
I created a character : class was chosen, nickname was invented. I log in game, choose server Tiamat, then choose "green outpost". I entered but there is only black screen. And shows only floating tips. What should i do?

#103 [Log in] Bug with log in game after create new character.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.7.3.1321 (64-bit)
**Steps to reproduce:**
1)  Create new character (Take name and class);
2)  Choose server "Tiamat";
3) Chose location "Green outpost"

**Expected result:**
Successed log in game.
**Actual result:**
Can't log in game. (Black screen)

**Comment by streamcode9** [comment]
_And shows only floating tips_ =>**It** shows only floating tips.

_Successed log in game._ => **Success** log in **to** game.

See how to use **login** verb: http://www.dictionary.com/browse/login?s=t
