### ISSUE TITLE
Issue with entrance in area

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#31]
https://dn.mail.ru/forums/showthread.php?t=52416&page=6
Довольно странная ошибка. Появилась вчера. На могу войти в Комариную Пристань. С Небесной Гавани или Ведьминой топи- сперва "загружается" минуты три. Потом появляется черный экран с надписью "Не удалось установить связь с сервером". Единственный способ попасть туда - в круговую, через скалистые горы-южный порт-пристань. Нигде в другом месте подобного не наблюдается.

Some strange bug. It appeared yesterday. I can't entrance to Mosquito pier. From Heavenly pier or Witch swamp - first loading three munutes, then appear black screen with writtening "Failed to connect with server". One way to entrance that area - in a circular through Rocky Mountains - South port - Pier. No more places where this bug was detected.

#104 [Area] Problem with entering location "Mosquito pier".
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.4.1.3110 (64-bit)
**Steps to reproduce:**
1. Go to the location "Heavenly pier" or "Witch swamp".
2. Try to enter location "Mosquito pier".

**Expected result:**
You are in the location "Mosquito pier".
**Actual result:**
Game can't load location "Mosquito pier" (Black screen).

**Comment by streamcode9** [comment]
_I can't entrance_ => I can't enter

_first loading three munutes_ => It is loading three minutes at first

_Failed to connect with server_ => Failed to connect `to` server

_One way to entrance_ => The only way to enter
