### ISSUE TITLE
Some issue with environment

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#32]
https://dn.mail.ru/forums/showthread.php?t=52416&page=6
Не знаю какого рода эта ошибка, но отпишусь здесь.
Почти каждый раз как я захожу в любой инстанс (на любом уровне сложности), практически сразу теряется всякое взаимодействие персонажа с окружением. Мобы останавливаются, а персонаж не может ни нанести урон, ни подобрать лут, ничего. Он может сколько угодно бегать, махать оружием, использовать умения, но ничего не затронет. Ни мобов, ни окружение.
К тому же, из инстанса нельзя попасть в город, или куда-то ещё. Работает только кнопка "Выйти из игры"

I don't know what type this bug, but i will write here.
Almost every time i entered any instance (on any difficulty), almost immediately i lose any collaboration with environment. Mobs are stop, character can't deal damage, i can't take loot, and do anything. My character can run as much as he wants, swing his weapon, use abilities, but he will affect nothing, neither mobs or environment.
Besides, from instance i can't go to town or somewhere else. Only button "Leave the game" works.

#105 [Environment] Problem with environment in instance.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.5.3.874 (64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 0.8
**Steps to reproduce:**
1) Enter any instance.

**Expected result:**
You can affect with environment.
**Actual result:**
You can't affect with environment.

**Comment by streamcode9** [comment]
_what type this bug_ => what is the bug type

_Mobs are stop_ => Mobs stop

_neither mobs or environment_ => neither mobs *nor* environment
