### ISSUE TITLE
No items in bag

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#33]
https://dn.mail.ru/forums/showthread.php?t=52416&page=14
Баг.
Покупаешь мешочек с самоцветами у Пьеро, где должны быть новые Полированные камни, открываешь, а он пустой. Хотя там должны быть камни или ртуть. 

Bug.
I buy bug with gems from Piero, where new polished stones must be. Open it but it is empty. Аlthough there is must been stones or mercury.

#105 [Trade] Bug with trade from Piero.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.5.4.7652 (64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 1.0
**Steps to reproduce:**
1. Come to Piero.
2. Open trade -> Buy bag with gems.
3. Open it.

**Expected result:**
Some polished stones or mercury.
**Actual result:**
Empty bag.

**Comment by streamcode9** [comment]
_there is must been_ => there must be
