### ISSUE TITLE
Bug with Partfinder skill 

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#34]
https://dn.mail.ru/forums/showthread.php?t=52416&page=16
Скилл "Иллюзорная стрела" работает не корректно. У следопыта.
Вместо того что бы сталкиваться с врагом и взрываться, она проходит сквозь него до текстур, сталкиваясь с предметом (Но не мобом) взрывается.

Проще говоря, вместо того что бы взрываться при контакте с мобом, она проходит насквозь. 
The Partfinder skill "Illusion arrow" doesn't work correctly. Instead of impact with mob, she walk throught him to textures, and expodes after impact with item (not mob).

#106 [Skill] Bug with Partfinder skill
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.5.6.981(64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 1.0
**Steps to reproduce:**
1. Take Partfinder hero.
2. Use skill "Illusion arrow" on enemy mob.

**Expected result:**
Arrow explodes after impact with mob.
**Actual result:**
Arrow walk throught mob.

**Comment by streamcode9** [comment]
_Instead of impact with mob_ => Instead of `hitting` a mob

_she walk_ => it(стрела - это неодущевленны предмет) walk**s**
