### ISSUE TITLE
Bug with quest and skill force of wickedness.

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#36]
http://forum.uwow.biz/topic/264160-sila-nechestivosti/
Что нужно делать: Нужно нажать на стол возле босса и превратиться в зомбака, после пить лужи, держа Темную Скорбь. После того как накопиться 100% энергии прожать скил и зарядить Темную Скорбь силой нечестивости.
Что происходит: Не пополняется энерегия когда пьешь лужи, следовательно скил не используется и задание нельзя пройти. Еще бывает что босс просто багается и становится неуязвимым 
Возможно я что-то не так делаю, но по оффу делается все так. Помогите пожалуйста.

What should I do: Need to cick on the table near the boss and turn into zombie. Then I need to dring from puddle by holding Dark Sorrow. After i get 100% energy, i need to cast skill and charge Dark Sorrow by using force of wickedness.
What happens: Energy doesn't charge when I drinking from the puddle, therefore skill doesn't work and i can't finish the quest. The boss bugs sometimes and become invulnerable.
Maybe i do somthing wrong? But all dealth like this at the official server. Help me please.

 #108 [Quest] Bug with quest and skill force of wickedness.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.1.3.1254(64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 1.0
**Steps to reproduce:**
1. Click on table near the boss -> turn into zombie.
2. Drink from puddle by holding Dark Sorrow.

**Expected result:**
After taking 100% energy cast skill force of wickedness and charge Dark Sorrow.
**Actual result:**
Energy doesn't charge.

**Comment by streamcode9** [comment]
by using,  by holding => **by** не нужен

when I drinking => when I **am** drinking
