### ISSUE TITLE
Experience issue

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#37]
https://forum.worldofseabattle.com/topic/413-%D0%BD%D0%B5%D1%82-%D0%B1%D0%BE%D0%BD%D1%83%D1%81%D0%B0-%D0%B7%D0%B0-%D1%83%D0%B1%D0%B8%D0%B9%D1%81%D1%82%D0%B2%D0%BE-%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B8%D1%85-%D0%BF%D0%BE-%D0%BB%D0%B2%D0%BB-%D0%BD%D0%BF%D1%81/
Доброго времени суток. Есть такая проблемка купил дня два назад торговое судно Flute , по акции один на один посоветовали плыть на Утёсы ветров бить босов, После убийства боса мне выдало сообщение что из за разницы кораблей я не получаю бонус, т.е. он мне не дал полный опыт и золото что с него падает.После трёх таких попыток вернулся на карту Высокие берега где НПС ниже лвл, тут всё нормально, все дает как положено.Вчера купил другой корабль Shaving Water. Поплыл на Утесы ветров ситуация повторилась, что с босами , что с простыми мобами, Тоже самое повторилось и на карте Рокотис нет бонуса из за разницы кораблей. Я бы всё понял если бы мой корабль был выше по лвл, но он ниже по уровню. Объясните пожалуйста эту ситуацию может тут так задумано, но на сколько мне позволяет мне мой опыт в играх такого быть не должно. 

Good day. I have a problem. I bought a trade ship "Flute" two days ago. On the stock one on one i get the advice to swim on the "Cliffs of winds" and beat the bosses. After i killed the boss i have got a message where i saw that i have got less experience because we had different ships. After three attempts i went back to the "Tall coast", where NPC have lower level. All is good there, i get full experience and gold. Yesterday i bought another ship "Shaving water". I swam to the "Cliffs of winds" and had the same situation with the bosses and with simple mobs. I had same situation on the "Rokotis", i had no bonuses because of different ships. I understand if i had higher level ship, but my ship have lower level. Explain me this situation please. Maybe, you concived this, but my experience says that is wrong.

#108 [Process] Less experience from the boss.
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.0.2.235(64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 1.0
**Steps to reproduce:**
1. Take ship "Flute".
2. Swim to the "Cliffs of winds".
3. Kill the boss.

**Expected result:**
Normal experience and gold drop from the boss
**Actual result:**
Less experience and gold drop from the boss.

**Comment by streamcode9** [comment]
It is ok.
