### ISSUE TITLE
Bug with fort towers

### ISSUE THREAD

**Issue by Unstoppable1988** [Unstoppable1988/Exercises#38]
https://forum.worldofseabattle.com/topic/427-%D0%B1%D0%B0%D1%88%D0%BD%D0%B8-%D0%B3%D0%B8%D0%BB%D1%8C%D0%B4%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D1%84%D0%BE%D1%80%D1%82%D0%B0/
Здравствуйте, заметил такой баг. Башни форта  были уничтожены и не восстановились даже спустя  день. Все ресурсы в форте гильдии обнулились, а сам форт перестал их производить. Закинул туда немного ресурсов и производство возобновилось. Башни стоят, но когда к ним подплываешь, то они падают. В меню форта все в порядке, вся защита выкачана на максимум, а на самом то деле форт беззащитен, что это за дела ??

Hi, i found the bug. Fort towers was destroyed and didn't recovered even after a day. All resources in fort guild came to zero, and fort stop produce resources. I threw some resources to the fort and fort started to produce resources again. Towers are standing but if i swim to them they are fallen down. All is good in the fort menu, all defence pumped to maximum. But at the same time fort have no deffence. What the fuck?

#109 [Mechanic] No defence from the fort towers
**Environment:**
Device: Laptop Lenovo G590
OS: Windows 7 x64 SP1
Game Version: 1.0.3.781(64-bit)
Connection type: LAN 100 Mb/s
Reproducibility Rate: 0.8
**Steps to reproduce:**
1. Enemy must destroy fort towers.
2. Throw resources to the fort.
3. Wait for one day.

**Expected result:**
Towers defend the fort.
**Actual result:**
Towers are fallen down if i swim to them.

**Comment by streamcode9** [comment]
_i_ => **I** 
It must be uppercase!!!
See this article https://en.wikipedia.org/wiki/I_(pronoun)
