### ISSUE TITLE
Largest palindrome product

### ISSUE THREAD

**Issue by streamcode9** [Unstoppable1988/Exercises#7]
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

**Comment by Unstoppable1988** [comment]
namespace Exercises
{
    class Palindrome
    {
        public static int Chislo()
        {
            for (int x = 100; x < 1000; x++)
            {
                for (int y = 100; y < 1000; y++)
                {
                    return x * y;
                }
                string s = x.ToString();
                if (s[0] == s[5] && s[1] == s[4] && s[3] == s[2])
                {
                    ;
                }
            }
        }
       public static void Run();

        Console.WriteLine();
                    Console.ReadLine();

**Comment by Unstoppable1988** [comment]
Completed
