### ISSUE TITLE
Smallest multiple

### ISSUE THREAD

**Issue by streamcode9** [Unstoppable1988/Exercises#8]
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

**Comment by Unstoppable1988** [comment]
namespace Exercises
{
    class Smalest_multiplie
    {
        public static bool IsDividible(int z)
        {
            for (int a = 1; a < 21; a++)
            {
                if (z % a != 0)
                {
                    return false;
                }
            }
            return true;
        }
        public static void Run()
        {
            public static bool Compilation()
            {
                for (int x = 1; ; x++)
                {
                    if (IsDividible(x) == false)
                    {
                        return true;
                    }
                }
                return false;
            }

            Console.WriteLine();
            Console.ReadLine();
        }
    }
}

**Comment by Unstoppable1988** [comment]
Completed
